var myName = "My Name Is Aamir Khan Channa";
console.log(myName);
var myFather = "My Father Name Is Ahmed Khan Channa";
console.log(myFather);
var favourateColor = "My Favourite Color Is Black";
console.log(favourateColor);
var isAge = "Iam Twenty Five Years Old";
console.log(isAge);
var howOld = 25;
console.log(howOld);
var myVillage = "My Village Is So Beautifull";
console.log(myVillage);
var areYoustudent = "I Am Student In Governor Initiative IT Program AI WEB 3.O Metaverse";
console.log(areYoustudent);
var istudent = true;
console.log(istudent);
